### ISSUE TITLE
Easily importing literture references by only specifying a DOI or WD qid

### ISSUE THREAD

**Issue by bjschembera** [MaRDI4NFDI/MaRDIRoadmap#104]
**Issue description**:
As discussed in the TA4-TA5 meeting on Sept 23rd, 2025, a mechanism that creates an entry for a literature reference (with journal, authors, etc) upon just specifying a DOI would be helpful to the users. This we imagine to be similiar to the beam me up tool maybe
 
**TODOS**: 

tbd

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by timconrad** [comment]
Similar to the "Beam-me-up-Tool" ( https://factgrid.wikidata.dbis.rwth-aachen.de/ ).

**Comment by timconrad** [comment]
Some tool candidates: 
* https://github.com/magnusmanske/papers
* https://www.wikidata.org/wiki/Wikidata:SourceMD

Potential workflow: 
* Add paper to WikiData
* Copy item to MaRDI

**Comment by timconrad** [comment]
Technical idea: run a Flask server inside an K8 pod that accepts REST calls that call the needed Python functions.

**Comment by physikerwelt** [comment]
@LizzAlice, can you send an update about the status of this? The WIAS urgently needs this.

**Comment by LizzAlice** [comment]
@physikerwelt Oh sorry, this has been merged 2 weeks ago, you can reach it internally. The code is in https://github.com/MaRDI4NFDI/docker-importer/tree/main/flask_app . This should work for the doi and also for wikidata items as mentioned in #104

**Comment by physikerwelt** [comment]
@LizzAlice ok, I'll try running the import locally as described in the readme. However, for production use, we also need a variable that points to the actual importer URL. Do we have a stable (internal) URL that can be reached from the wikibase instance?

**Comment by eloiferrer** [comment]
I think you can skip running it locally and do this directly on staging.

To import a wikidata item you just need to send a POST request to http://importer/import/wikidata with the qids from the data parameter:
```
data = {"qids": ["Q42", "Q5"]}
response = requests.post("http://importer/import/wikidata", json=data)
```

For the DOI it would be:
```
data = {"dois": ["10.1126/science.1241224"]}
response = requests.post("http://importer/import/doi", json=data)
```

PS. In staging the endpoints are actually http://staging-importer/import/wikidata and http://staging-importer/import/doi

**Comment by physikerwelt** [comment]
@eloiferrer ok, I'll try, but I believe it will be difficult to develop the frontend without actual values from the backend that correspond to the developer instance.

**Comment by eloiferrer** [comment]
What do you mean with actual values?

I guess you can try it locally by just sending the request to the importer container, with the corresponding endpoint mentioned above.

**Comment by physikerwelt** [comment]
I mean values that correspond to the state of the wiki that sends the request. For example, what should happen if I try to import a DOI that already exists? I believe that would be hard to test... but we'll see

**Comment by eloiferrer** [comment]
The importer code checks already if the wikidata item or the DOI already exist. So they won't create a duplicate and will just return to corresponding QID of the already existing item.

**Comment by physikerwelt** [comment]
I imported the first doi

https://portal.mardi4nfdi.de/wiki/Item:Q6775801

@LizzAlice I think there are very few fields. Maybe you can look into it?

**Comment by physikerwelt** [comment]
Also I think in the next version the API should have a field for the username who requested the import, so that this can be used either as author (to also undo changes later)

**Comment by physikerwelt** [comment]
I did send
```
{"qids":["Q117355636"]}
```
to `http://importer/import/wikidata`

and got back a 500 error without any additional information what I was doing wrong

```
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by physikerwelt** [comment]
The first frontend version is there for https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MathSearch/+/1208331

**Comment by LizzAlice** [comment]
So if you say the first frontend version is there, does that mean it worked after all?

**Comment by physikerwelt** [comment]
It does send the request, but the results were not satisfactory as described above:

1) doi: https://portal.mardi4nfdi.de/wiki/Item:Q6775801
2) wikidata: error 500

**Comment by physikerwelt** [comment]
Here the output I see for my wikidata request
```
[2025-11-21  14:05:48]	importing entity Q117355636
[2025-11-21  14:05:49]	[2025-11-21 13:05:49 +0000] [133] [INFO] Booting worker with pid: 133
[2025-11-21  14:06:21]	ERROR:wikibaseintegrator.entities.baseentity:Error while writing to the Wikibase instance
[2025-11-21  14:06:21]	Traceback (most recent call last):
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/entities/baseentity.py", line 287, in _write
[2025-11-21  14:06:21]	    json_result: dict = edit_entity(data=data, id=entity_id, type=self.type, summary=summary, clear=clear, is_bot=is_bot, allow_anonymous=allow_anonymous,
[2025-11-21  14:06:21]	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 339, in edit_entity
[2025-11-21  14:06:21]	    return mediawiki_api_call_helper(data=params, is_bot=is_bot, **kwargs)
[2025-11-21  14:06:21]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 177, in mediawiki_api_call_helper
[2025-11-21  14:06:21]	    raise ValueError("allow_anonymous can't be False and login is None at the same time.")
[2025-11-21  14:06:21]	ValueError: allow_anonymous can't be False and login is None at the same time.
[2025-11-21  14:06:21]	ERROR:flask_app.app:Exception on /import/wikidata [POST]
[2025-11-21  14:06:21]	Traceback (most recent call last):
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
[2025-11-21  14:06:21]	    response = self.full_dispatch_request()
[2025-11-21  14:06:21]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
[2025-11-21  14:06:21]	    rv = self.handle_user_exception(e)
[2025-11-21  14:06:21]	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
[2025-11-21  14:06:21]	    rv = self.dispatch_request()
[2025-11-21  14:06:21]	         ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
[2025-11-21  14:06:21]	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[2025-11-21  14:06:21]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/app/flask_app/app.py", line 27, in import_wikidata
[2025-11-21  14:06:21]	    wdi = WikidataImporter()
[2025-11-21  14:06:21]	          ^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 36, in __init__
[2025-11-21  14:06:21]	    self.setup()
[2025-11-21  14:06:21]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 47, in setup
[2025-11-21  14:06:21]	    self.wikidata_QID = self._init_wikidata_QID()
[2025-11-21  14:06:21]	                        ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 230, in _init_wikidata_QID
[2025-11-21  14:06:21]	    return wikidata_QID or prop.write(login=self.api.login, as_new=True).id
[2025-11-21  14:06:21]	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/entities/property.py", line 147, in write
[2025-11-21  14:06:21]	    json_data = super()._write(data=self.get_json(), **kwargs)
[2025-11-21  14:06:21]	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/entities/baseentity.py", line 287, in _write
[2025-11-21  14:06:21]	    json_result: dict = edit_entity(data=data, id=entity_id, type=self.type, summary=summary, clear=clear, is_bot=is_bot, allow_anonymous=allow_anonymous,
[2025-11-21  14:06:21]	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 339, in edit_entity
[2025-11-21  14:06:21]	    return mediawiki_api_call_helper(data=params, is_bot=is_bot, **kwargs)
[2025-11-21  14:06:21]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:06:21]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 177, in mediawiki_api_call_helper
[2025-11-21  14:06:21]	    raise ValueError("allow_anonymous can't be False and login is None at the same time.")
[2025-11-21  14:06:21]	ValueError: allow_anonymous can't be False and login is None at the same time.
[2025-11-21  14:08:17]	ERROR:wikibaseintegrator.entities.baseentity:Error while writing to the Wikibase instance
[2025-11-21  14:08:17]	Traceback (most recent call last):
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/entities/baseentity.py", line 287, in _write
[2025-11-21  14:08:17]	    json_result: dict = edit_entity(data=data, id=entity_id, type=self.type, summary=summary, clear=clear, is_bot=is_bot, allow_anonymous=allow_anonymous,
[2025-11-21  14:08:17]	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 339, in edit_entity
[2025-11-21  14:08:17]	    return mediawiki_api_call_helper(data=params, is_bot=is_bot, **kwargs)
[2025-11-21  14:08:17]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 177, in mediawiki_api_call_helper
[2025-11-21  14:08:17]	    raise ValueError("allow_anonymous can't be False and login is None at the same time.")
[2025-11-21  14:08:17]	ValueError: allow_anonymous can't be False and login is None at the same time.
[2025-11-21  14:08:17]	ERROR:flask_app.app:Exception on /import/wikidata [POST]
[2025-11-21  14:08:17]	Traceback (most recent call last):
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
[2025-11-21  14:08:17]	    response = self.full_dispatch_request()
[2025-11-21  14:08:17]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
[2025-11-21  14:08:17]	    rv = self.handle_user_exception(e)
[2025-11-21  14:08:17]	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
[2025-11-21  14:08:17]	    rv = self.dispatch_request()
[2025-11-21  14:08:17]	         ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
[2025-11-21  14:08:17]	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[2025-11-21  14:08:17]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/app/flask_app/app.py", line 27, in import_wikidata
[2025-11-21  14:08:17]	    wdi = WikidataImporter()
[2025-11-21  14:08:17]	          ^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 36, in __init__
[2025-11-21  14:08:17]	    self.setup()
[2025-11-21  14:08:17]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 47, in setup
[2025-11-21  14:08:17]	    self.wikidata_QID = self._init_wikidata_QID()
[2025-11-21  14:08:17]	                        ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 230, in _init_wikidata_QID
[2025-11-21  14:08:17]	    return wikidata_QID or prop.write(login=self.api.login, as_new=True).id
[2025-11-21  14:08:17]	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/entities/property.py", line 147, in write
[2025-11-21  14:08:17]	    json_data = super()._write(data=self.get_json(), **kwargs)
[2025-11-21  14:08:17]	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/entities/baseentity.py", line 287, in _write
[2025-11-21  14:08:17]	    json_result: dict = edit_entity(data=data, id=entity_id, type=self.type, summary=summary, clear=clear, is_bot=is_bot, allow_anonymous=allow_anonymous,
[2025-11-21  14:08:17]	                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 339, in edit_entity
[2025-11-21  14:08:17]	    return mediawiki_api_call_helper(data=params, is_bot=is_bot, **kwargs)
[2025-11-21  14:08:17]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  14:08:17]	  File "/usr/local/lib/python3.11/site-packages/wikibaseintegrator/wbi_helpers.py", line 177, in mediawiki_api_call_helper
[2025-11-21  14:08:17]	    raise ValueError("allow_anonymous can't be False and login is None at the same time.")
[2025-11-21  14:08:17]	ValueError: allow_anonymous can't be False and login is None at the same time.

**Comment by LizzAlice** [comment]
Eloi pulled a new image version to production and tried importing with the wikidata import script, which worked, and that should work the same as the app. Can you try again? Or alternatively tell me where you put the frontend app?

**Comment by LizzAlice** [comment]
As for doi, please try with a doi that is not as recent or not a zenodo doi. I will make it pull from zenodo/arxiv instead of crossref next week.

**Comment by physikerwelt** [comment]
> Eloi pulled a new image version to production and tried importing with the wikidata import script, which worked, and that should work the same as the app. Can you try again? Or alternatively tell me where you put the frontend app?

https://portal.mardi4nfdi.de/wiki/Special:Version shows 0.2.0 (11edb2f) 23:05, 5 November 2025 for MathSearch. It should have the version from today.

**Comment by eloiferrer** [comment]
I meant a new image for the importer (which is the one throwing the error above). The wikibase image is still the same.

**Comment by physikerwelt** [comment]
I just finished a commit to workarond https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MathSearch/+/1208391 ... maybe it makes sense to wait for that to be merged as well and then try the new wikibase image...

I will test locally...

**Comment by physikerwelt** [comment]
> I meant a new image for the importer (which is the one throwing the error above). The wikibase image is still the same.

now I realize there is a second pod (importer-api), but this is not the one to use?

**Comment by eloiferrer** [comment]
No, this is another unrelated api to run imports from any other machine through https://github.com/MaRDI4NFDI/mardiclient

**Comment by physikerwelt** [comment]
mh, it still fails for me

Can you try it yourself using curl? I guess this would be more efficient

Error log
```
2025-11-21  17:17:34]	[2025-11-21 16:17:34 +0000] [7] [INFO] Worker exiting (pid: 7)
[2025-11-21  17:17:34]	importing entity Q117355636
[2025-11-21  17:17:34]	[2025-11-21 16:17:34 +0000] [66] [INFO] Booting worker with pid: 66
[2025-11-21  17:19:36]	[2025-11-21 16:19:36 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
[2025-11-21  17:19:36]	[2025-11-21 16:19:36 +0000] [8] [ERROR] Error handling request //import/wikidata
[2025-11-21  17:19:36]	Traceback (most recent call last):
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
[2025-11-21  17:19:36]	    self.handle_request(listener, req, client, addr)
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
[2025-11-21  17:19:36]	    respiter = self.wsgi(environ, resp.start_response)
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
[2025-11-21  17:19:36]	    return self.wsgi_app(environ, start_response)
[2025-11-21  17:19:36]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
[2025-11-21  17:19:36]	    response = self.full_dispatch_request()
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
[2025-11-21  17:19:36]	    rv = self.dispatch_request()
[2025-11-21  17:19:36]	         ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
[2025-11-21  17:19:36]	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[2025-11-21  17:19:36]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/app/flask_app/app.py", line 31, in import_wikidata
[2025-11-21  17:19:36]	    imported_q = wdi.import_entities(q)
[2025-11-21  17:19:36]	                 ^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 291, in import_entities
[2025-11-21  17:19:36]	    self._convert_claim_ids(entity)
[2025-11-21  17:19:36]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 609, in _convert_claim_ids
[2025-11-21  17:19:36]	    new_qualifiers = self._get_qualifiers(c)
[2025-11-21  17:19:36]	                     ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 698, in _get_qualifiers
[2025-11-21  17:19:36]	    new_qual_val_id = self._import_claim_entities(
[2025-11-21  17:19:36]	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 472, in _import_claim_entities
[2025-11-21  17:19:36]	    local_id = entity.exists()
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/mardiclient/mardi_entities.py", line 95, in exists
[2025-11-21  17:19:36]	    QID_list = self.get_QID()
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/mardiclient/mardi_entities.py", line 297, in get_QID
[2025-11-21  17:19:36]	    response = requests.get(
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
[2025-11-21  17:19:36]	    return request("get", url, params=params, **kwargs)
[2025-11-21  17:19:36]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
[2025-11-21  17:19:36]	    return session.request(method=method, url=url, **kwargs)
[2025-11-21  17:19:36]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
[2025-11-21  17:19:36]	    resp = self.send(prep, **send_kwargs)
[2025-11-21  17:19:36]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
[2025-11-21  17:19:36]	    r = adapter.send(request, **kwargs)
[2025-11-21  17:19:36]	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 644, in send
[2025-11-21  17:19:36]	    resp = conn.urlopen(
[2025-11-21  17:19:36]	           ^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[2025-11-21  17:19:36]	    response = self._make_request(
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 534, in _make_request
[2025-11-21  17:19:36]	    response = conn.getresponse()
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 565, in getresponse
[2025-11-21  17:19:36]	    httplib_response = super().getresponse()
[2025-11-21  17:19:36]	                       ^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/http/client.py", line 1395, in getresponse
[2025-11-21  17:19:36]	    response.begin()
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
[2025-11-21  17:19:36]	    version, status, reason = self._read_status()
[2025-11-21  17:19:36]	                              ^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/http/client.py", line 286, in _read_status
[2025-11-21  17:19:36]	    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[2025-11-21  17:19:36]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/socket.py", line 718, in readinto
[2025-11-21  17:19:36]	    return self._sock.recv_into(b)
[2025-11-21  17:19:36]	           ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:19:36]	  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
[2025-11-21  17:19:36]	    sys.exit(1)
[2025-11-21  17:19:36]	SystemExit: 1
[2025-11-21  17:19:36]	[2025-11-21 16:19:36 +0000] [8] [INFO] Worker exiting (pid: 8)
[2025-11-21  17:19:36]	importing entity Q117355636
[2025-11-21  17:19:36]	[2025-11-21 16:19:36 +0000] [83] [INFO] Booting worker with pid: 83
[2025-11-21  17:20:29]	[2025-11-21 16:20:29 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:66)
[2025-11-21  17:20:29]	[2025-11-21 16:20:29 +0000] [66] [ERROR] Error handling request //import/wikidata
[2025-11-21  17:20:29]	Traceback (most recent call last):
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
[2025-11-21  17:20:29]	    self.handle_request(listener, req, client, addr)
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
[2025-11-21  17:20:29]	    respiter = self.wsgi(environ, resp.start_response)
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
[2025-11-21  17:20:29]	    return self.wsgi_app(environ, start_response)
[2025-11-21  17:20:29]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
[2025-11-21  17:20:29]	    response = self.full_dispatch_request()
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
[2025-11-21  17:20:29]	    rv = self.dispatch_request()
[2025-11-21  17:20:29]	         ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
[2025-11-21  17:20:29]	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[2025-11-21  17:20:29]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/app/flask_app/app.py", line 31, in import_wikidata
[2025-11-21  17:20:29]	    imported_q = wdi.import_entities(q)
[2025-11-21  17:20:29]	                 ^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 291, in import_entities
[2025-11-21  17:20:29]	    self._convert_claim_ids(entity)
[2025-11-21  17:20:29]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 609, in _convert_claim_ids
[2025-11-21  17:20:29]	    new_qualifiers = self._get_qualifiers(c)
[2025-11-21  17:20:29]	                     ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 698, in _get_qualifiers
[2025-11-21  17:20:29]	    new_qual_val_id = self._import_claim_entities(
[2025-11-21  17:20:29]	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/mardi_importer/mardi_importer/wikidata/WikidataImporter.py", line 472, in _import_claim_entities
[2025-11-21  17:20:29]	    local_id = entity.exists()
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/mardiclient/mardi_entities.py", line 95, in exists
[2025-11-21  17:20:29]	    QID_list = self.get_QID()
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/mardiclient/mardi_entities.py", line 297, in get_QID
[2025-11-21  17:20:29]	    response = requests.get(
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
[2025-11-21  17:20:29]	    return request("get", url, params=params, **kwargs)
[2025-11-21  17:20:29]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
[2025-11-21  17:20:29]	    return session.request(method=method, url=url, **kwargs)
[2025-11-21  17:20:29]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
[2025-11-21  17:20:29]	    resp = self.send(prep, **send_kwargs)
[2025-11-21  17:20:29]	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
[2025-11-21  17:20:29]	    r = adapter.send(request, **kwargs)
[2025-11-21  17:20:29]	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 644, in send
[2025-11-21  17:20:29]	    resp = conn.urlopen(
[2025-11-21  17:20:29]	           ^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[2025-11-21  17:20:29]	    response = self._make_request(
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 534, in _make_request
[2025-11-21  17:20:29]	    response = conn.getresponse()
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 565, in getresponse
[2025-11-21  17:20:29]	    httplib_response = super().getresponse()
[2025-11-21  17:20:29]	                       ^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/http/client.py", line 1395, in getresponse
[2025-11-21  17:20:29]	    response.begin()
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
[2025-11-21  17:20:29]	    version, status, reason = self._read_status()
[2025-11-21  17:20:29]	                              ^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/http/client.py", line 286, in _read_status
[2025-11-21  17:20:29]	    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[2025-11-21  17:20:29]	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/socket.py", line 718, in readinto
[2025-11-21  17:20:29]	    return self._sock.recv_into(b)
[2025-11-21  17:20:29]	           ^^^^^^^^^^^^^^^^^^^^^^^
[2025-11-21  17:20:29]	  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
[2025-11-21  17:20:29]	    sys.exit(1)
[2025-11-21  17:20:29]	SystemExit: 1
[2025-11-21  17:20:29]	[2025-11-21 16:20:29 +0000] [66] [INFO] Worker exiting (pid: 66)
[2025-11-21  17:20:29]	importing entity Q117355636
[2025-11-21  17:20:30]	[2025-11-21 16:20:30 +0000] [100] [INFO] Booting worker with pid: 100

**Comment by eloiferrer** [comment]
This is now a different error though. This is something wrong in the logic of the importer. Which entity were you importing?

**Comment by physikerwelt** [comment]
I deployed the frontend via git to https://portal.mardi4nfdi.de/wiki/Special:ImportFromPid 

> [2025-11-21  17:17:34]	importing entity Q117355636

**Comment by timconrad** [comment]
@LizzAlice Please check whether this is related to the importer

**Comment by LizzAlice** [comment]
@physikerwelt Where exactly did you get that error log from?

**Comment by physikerwelt** [comment]
@LizzAlice this is from the importer pod

**Comment by LizzAlice** [comment]
@physikerwelt Ok, the problem should be solved now, the earlier problem was because the login env vars were missing from the importer pod. The later problem was because we were going over the connection limit for our user in mariadb. I noticed however that the frontend gives no feedback over when the query finishes?

**Comment by physikerwelt** [comment]
very good. I didn't implement the feedback yet. With return values at hand this will be easier:-)

**Comment by physikerwelt** [comment]
@LizzAlice I tested Q136348635 and don't see any errors, but also I don't find the item.
The API returns the following payload
```
{"count":1,"errors":[],"imported":true,"qids":["Q136348635"],"results":[{"qid":{},"result":true}]}
```
I could turn that into HTML, but still I would like to see the qid on the mardi portal that has been created.

**Comment by LizzAlice** [comment]
@physikerwelt I found the first problem: Your item had a default value for all languages, which the importer could not handle because it specifically wanted a label in english or german, when I copied it to be an actual value in english, it failed upwards to the next error that I also got for another item.

**Comment by LizzAlice** [comment]
Before continuing with this, we need to stabilize the db, a lot of attempts are failing because the db is not reachable.

**Comment by physikerwelt** [comment]
> Before continuing with this, we need to stabilize the db, a lot of attempts are failing because the db is not reachable.

While we are at this, we can add a reasonable error message for that case;-)

What do you mean by "the DB" is not reachable. I would need some more details to help.

**Comment by LizzAlice** [comment]
@physikerwelt This is fixed, there was a problem with stale connections, now there is a new internal error (: What do you mean with a reasonable error message?

**Comment by physikerwelt** [comment]
Ah this "internal error" ... that one is really bad.

Some thoughts on error messages
https://ux.stackexchange.com/a/39108

For a user it might be interesting if one can try for example a doi, or another wikidata id. See if the problem is on the wikidata end, or on the MaRDI end.

**Comment by LizzAlice** [comment]
Sure, that is all in the the error messages that should be in the response, or are they not in there? That you got not error previously was because of the language bug. I find the error messages reasonably clear

**Comment by physikerwelt** [comment]
I get the following result for the example mentioned above
```
{"count":1,"errors":[],"imported":true,"qids":["Q136348635"],"results":[{"qid":"Q6821077","result":true}]}
```
I don't see any internal errors.

**Comment by LizzAlice** [comment]
Great, maybe you can use that to customize the api frontend? Yes, the errors get triggered in a weird way and the item still gets imported. The internal error I was talking about is already fixed. Right now, I am trying to figure out why your api frontend in staging does not seem to hit the api backend...

**Comment by physikerwelt** [comment]
Ah I see that's a 200 return code. So it was successful.

Before I start on working the ui for the happy case I have some questions.

Can you return the results as an associative array.

"results":{"Q136348635":{"qid":"Q6821077","result":true}}

that would simplify the implementation.

Maybe result can be a string? Success, Failed, Did exist, warning whatever?

Then it's good enough for me to evaluate the results.

I would also like to pass the username of the importer, so that the item are atributed to the person requesting the import and not to the importer bot.

**Comment by LizzAlice** [comment]
I will look into it, but do you have any idea about staging?

**Comment by physikerwelt** [comment]
I think staging is not properly configured. It uses the default url `http://importer` which can be altered using the setting `$MathSearchImporterUrl`. Should that be different for staging @eloiferrer ?

**Comment by eloiferrer** [comment]
yes, it should be http://staging-importer

**Comment by LizzAlice** [comment]
> Ah I see that's a 200 return code. So it was successful.
> 
> Before I start on working the ui for the happy case I have some questions.
> 
> Can you return the results as an associative array.
> 
> "results":{"Q136348635":{"qid":"Q6821077","result":true}}
> 
> that would simplify the implementation.
> 
> Maybe result can be a string? Success, Failed, Did exist, warning whatever?
> 
> Then it's good enough for me to evaluate the results.
> 
> I would also like to pass the username of the importer, so that the item are atributed to the person requesting the import and not to the importer bot.

Done, status can be success, not_imported or error. Error is returned as a string if it exists

**Comment by LizzAlice** [comment]
@physikerwelt I tried to check if I can see the importer feedback when importing from wikidata on staging, but it just displayed an empty page?

**Comment by physikerwelt** [comment]
Did you deploy the latest image there? 
https://staging.mardi4nfdi.org/wiki/Special:Version shows 
> 0.2.0 (0698426) 08:15, 29 November 2025

So I guess this is not yet the latest image with commit [7785030](https://github.com/wikimedia/mediawiki-extensions-MathSearch/commit/778503096d50d26688c46998e066ad41e1bb83be).

**Comment by LizzAlice** [comment]
@physikerwelt I only deployed the new importer, I thought you did that :) Which image is it?

**Comment by physikerwelt** [comment]
https://github.com/MaRDI4NFDI/docker-wikibase ... I still can't deploy with confidence. So I am a bit hesitant to do it myself, if I can't promise to be around for the next few hours to monitor the effects.

**Comment by physikerwelt** [comment]
Is there an option to access the VPN from a phone? That would give more flexibility to fix things while travelling.

**Comment by LizzAlice** [comment]
Ok, you can now test in staging for wikidata import as well as doi import for dois that are not from arxiv or zenodo.

**Comment by physikerwelt** [comment]
<img width="1507" height="858" alt="Image" src="https://github.com/user-attachments/assets/a4ee9825-48b8-4930-84a8-5afdaf1e19d4" /> That's what I see for the test input

**Comment by physikerwelt** [comment]
I created https://staging.mardi4nfdi.org/w/index.php?title=Module:ImportFromPidFeedback&oldid=30512 and then the result is the following

<img width="1507" height="858" alt="Image" src="https://github.com/user-attachments/assets/93bfe179-4e58-4a62-aa62-5189a44426fe" />

which reveals that I did not use the correct type 🦙

**Comment by LizzAlice** [comment]
Nice, that means my fix worked, before that would have thought the qid was a doi and created an item for that xD

**Comment by physikerwelt** [comment]
Now the item [Q14071](https://staging.mardi4nfdi.org/wiki/Item:Q14071) was created, but not the profile page.

**Comment by LizzAlice** [comment]
The profile page is always created using your profile page creation script, no?

**Comment by physikerwelt** [comment]
No, it should now be created automatically, once the property is set. I have tested it in production, and it does work. Maybe staging is not configured correctly?

**Comment by LizzAlice** [comment]
Ah you mean the property? Well, the wikidata importer does not know what kind of a page this is supposed to be, we would either have to pass that with the request or set defaults based on instance.

**Comment by LizzAlice** [comment]
Ok, if the problem is that when you manually set the property, the profile page should be created automatically and that works in production but not in staging, then I don't know why it doesn't.

**Comment by physikerwelt** [comment]
> Ok, if the problem is that when you manually set the property, the profile page should be created automatically and that works in production but not in staging, then I don't know why it doesn't.

Because the P and Q values might be different. For local testing, I always use the same P and Q numbers that we have in production.

We have the

 		"MathProfileQueries": {
			"person": "?item wdt:P31 wd:Q57162",
			"formula": "?item wdt:P31 wd:Q1025939",
			"publication": "?item wdt:P1451 ?zblno",
			"software": "?item wdt:P13 ?swmathID"
		}, 

that would set the respective profile type

		"MathString2QMap": {
			"P1460": {
				"academic_discipline": "Q6534268",
				"algorithm": "Q6503323",
				"community": "Q6205095",
				"dataset": "Q5984635",
				"formula": "Q5981696",
				"model": "Q6534270",
				"person": "Q5976445",
				"publication": "Q5976449",
				"quantity": "Q6534271",
				"research_problem": "Q6534269",
				"service": "Q6503324",
				"software": "Q5976450",
				"task": "Q6534272",
				"theorem": "Q6534201",
				"workflow": "Q6534216"
			},

However, all those Ps and Qs don't exist in staging, therefore we would need to adjust the staging config or import properties and items from the main portal.

How should we proceed? Is anyone motivated to adjust the config for staging?

The missing bit to implement is to run the math profile queries

 		"MathProfileQueries": {
			"person": "?item wdt:P31 wd:Q57162",
			"formula": "?item wdt:P31 wd:Q1025939",
			"publication": "?item wdt:P1451 ?zblno",
			"software": "?item wdt:P13 ?swmathID"
		}, 

and add the property (this can be either be done by the importer or the front-end) and then test again if the profile page is created.

**Comment by LizzAlice** [comment]
Arxiv and zenodo dois now also work

**Comment by LizzAlice** [comment]
@physikerwelt So for the frontend there is this documentation: https://mardi4nfdi.github.io/docker-importer/flask_endpoints.html       
To change the submission endpoint, it is just appending async to the former endpoint. Then, there is /import/workflow_status, which might also contain the result, or else /import/workflow_result. My idea was that the process is as follows: submission to async endpoint -> get back the job id from that -> get redirected to a status page that periodically checks if the status is completed yet -> if yes, display link to resulting QID(s). Is there something I can do to help you with that?

**Comment by physikerwelt** [comment]
@LizzAlice I did use port 8000 before, but the documentation says port 80. I can get a response with port 8000, is that a mistake in the docu or am I running another service?

**Comment by physikerwelt** [comment]
I am getting a positive resonse in the form
```
{"message":"Wikidata import process started in background","flow_id":"5c0b4f01-3589-4e37-8414-552fb656316d","deployment_id":"b1d9c17f-bcae-4ec2-980a-512b424e402c","id":"fa415871-d697-4afa-936c-c5d852b5cda5","status":"accepted","qids_queued":["Q6722"]} 
```

**Comment by physikerwelt** [comment]
However, the check endpoint seems to be broken currently

{"details":"404 Client Error: Not Found for url: http://prefect-server:4200/api/flow_runs/5c0b4f01-3589-4e37-8414-552fb656316d","error":"prefect api error"}

**Comment by physikerwelt** [comment]
> However, the check endpoint seems to be broken currently
> 
> {"details":"404 Client Error: Not Found for url: [http://prefect-server:4200/api/flow_runs/5c0b4f01-3589-4e37-8414-552fb656316d","error":"prefect](http://prefect-server:4200/api/flow_runs/5c0b4f01-3589-4e37-8414-552fb656316d%22,%22error%22:%22prefect) api error"}

ok that means wrong id... with the correct id I get
```
{
  "id": "fa415871-d697-4afa-936c-c5d852b5cda5",
  "state": "CRASHED",
  "state_name": "Crashed",
  "timestamp": "2026-01-31T14:14:16.255015Z"
}

**Comment by physikerwelt** [comment]
> Is there something I can do to help you with that?

I think it would be more flexible and maintainable if we would do most (all of it in LUA).  See https://www.mediawiki.org/wiki/Extension:External_Data/Lua

**Comment by physikerwelt** [comment]
By the way, there is even https://en.wikipedia.org/wiki/Module:UnitTests for lua modules

**Comment by physikerwelt** [comment]
This has been deployed to production now

https://github.com/MaRDI4NFDI/portal-k8s/commit/c61d420d2c69c2323aafeb478210930db62f059c

Unfortunatley the WMF_13 version that is currently deployed had a bug https://phabricator.wikimedia.org/T415751 which I hot-fixed by running
```
root@wikibase-fpm-6677f44565-7qmld:/var/www/html/w# git fetch --no-recurse-submodules https://gerrit.wikimedia.org/r/mediawiki/core refs/changes/83/1234283/2 && git cherry-pick FETCH_HEAD -c
```
Note that --no-recurse-submodules  and -c are important here as we somwhow destroy git in production when installing modules of VE.

**Comment by physikerwelt** [comment]
### Status update for Monday 2.2.26:

https://portal.mardi4nfdi.de/wiki/Special:ImportFromPid calls the described API endpoint and https://portal.mardi4nfdi.de/wiki/Module:ImportFromPidFeedback parses the response.

However, I was not able to import items from that list

https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/151#issuecomment-3756555482

@LizzAlice can you test yourself and see if the frontend sends the correct request?

**Comment by LizzAlice** [comment]
@physikerwelt It appears something is broken in prefect, we are investigating.

**Comment by LizzAlice** [comment]
@physikerwelt Ok, it works again!
